apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: AWS-Cluster
  controllerUrl: "http://activesec.saas.appdynamics.com"
  account: "activesec"
  # docker image info
  image: "docker.io/appdynamics/cluster-agent:latest"
  serviceAccountName: appdynamics-cluster-agent
  nsToMonitorRegex: .*
  ### Uncomment the following line if you need pull secret
  #imagePullSecret: "<your-docker-pull-secret-name>"
  #
  stdoutLogging: "true"
